[tool.poetry]
name = "martelada"
version = "0.0.1"
description = ""
authors = ["Lucas Polo <pradopolo@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.8,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
